const TextResult = ({ result }) => {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center gap-8">
      <h1 className="text-2xl font-semibold">AI Detector: {
        result === "AI" ? "Your text is generated by"
        :
        result === "Human" ? "Your text is written by"
        :
        "Your text is crafted by"
      }
      </h1>
      <p className={`text-4xl font-bold ${result === 'AI' ? 'text-red-500' : result === 'Human' ? 'text-green-500' : 'text-yellow-500'}`}>{
        result === 'Mixed' ? 'Both AI and Human' : result
      }</p>
    </div>
  );
}

export default TextResult